services:
  postgres:
    build:
      context: .
      dockerfile: db/Dockerfile
    container_name: mail-lab-postgres
    environment:
      POSTGRES_DB: mail_lab_db
      POSTGRES_USER: mail_user
      POSTGRES_PASSWORD: mail_pass
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mail_user -d mail_lab_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
