components_manager:
    coro_pool:
        initial_size: 500
        max_size: 1000

    task_processors:
        main-task-processor:
            worker_threads: 4
            thread_name: api-worker
        fs-task-processor:
            worker_threads: 2
            thread_name: fs-worker

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: 8080
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: info
                    overflow_behavior: discard

        dns-client:
            fs-task-processor: fs-task-processor

        postgres-db:
            dbconnection: 'postgresql://mail_user:mail_pass@postgres:5432/mail_lab_db'
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            max_pool_size: 16
            min_pool_size: 4

        testsuite-support: {}

        handler-ping-text:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-signup:
            path: /api/v1/users
            method: POST
            task_processor: main-task-processor

        handler-login:
            path: /api/v1/auth/login
            method: POST
            task_processor: main-task-processor

        handler-user-lookup:
            path: /api/v1/users/by-login
            method: GET
            task_processor: main-task-processor

        handler-user-search:
            path: /api/v1/users/search
            method: GET
            task_processor: main-task-processor

        handler-folder-create:
            path: /api/v1/folders
            method: POST
            task_processor: main-task-processor

        handler-folder-list:
            path: /api/v1/folders
            method: GET
            task_processor: main-task-processor

        handler-message-create:
            path: /api/v1/folders/{folderId}/messages
            method: POST
            task_processor: main-task-processor

        handler-message-list:
            path: /api/v1/folders/{folderId}/messages
            method: GET
            task_processor: main-task-processor

        handler-message-read:
            path: /api/v1/messages/{messageId}
            method: GET
            task_processor: main-task-processor

        handler-swagger-page:
            path: /swagger
            method: GET
            task_processor: main-task-processor
            url_trailing_slash: strict-match

        handler-openapi:
            path: /openapi.yaml
            method: GET
            task_processor: main-task-processor
